version : "3.7"

services:
  mongo:
    image : mongo:4.4.5
    restart: always
    networks:
      - main
    volumes:
      - mongo-volume:/data/db

  app:
    build: .
    restart: always
    environment:
      DISCORD_TOKEN: "${DISCORD_TOKEN}"
      WEATHER_TOKEN: "${WEATHER_TOKEN}"
    depends_on:
      - mongo
    networks:
      - main

networks:
  main:
    driver : bridge

volumes:
  mongo-volume:
    driver: local
